CREATE USER setter WITH PASSWORD '123456';
GRANT CONNECT ON DATABASE scheduler TO setter;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO setter;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO setter;